version: '3.7'

networks:
  dnd-net:
    name: dnd-net
    driver: bridge

services:
  game_db:
    container_name: game_db
    image: postgres:15.8-alpine
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./.docker/game_db:/var/lib/postgresql/data
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  minio:
    container_name: bucket_manager
    image: quay.io/minio/minio:latest
    platform: linux/x86_64
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_REGION_NAME: ${MINIO_REGION_NAME}
      MINIO_CONFIG_ENV_FILE: '.env'
    command: server --console-address ":9001" /mnt/data
    volumes:
      - ./.docker/minio:/mnt/data
      - type: bind
        source: ./minio
        target: /etc/config_env
    ports:
      - '${MINIO_PORT_CONSOLE}:9001'
      - '${MINIO_PORT_HOST}:9000'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9001/minio/health/live']
      interval: 30s
      timeout: 20s
      retries: 3

  redis:
    container_name: game_redis
    image: redis:6
    restart: always
    ports:
      - '6379:6379'
